### PR TITLE
Log validator

### PR DESCRIPTION
**Pull request by jeevanjagadeesh**
https://github.com/rajeshgrs/dq-cli/issues/13

### CODE REVIEW

**Comment by jeevanjagadeesh** [comment]
@rajeshgrs , this PR is still WIP.  But do have a look.
Xml file is created with pug template, currently the testcase data is hardcode. will change to read xls and log file.
 
command - node dqCliLogReader.js

image

**Comment by rajeshgrs** [comment]
@jeevanjagadeesh , Looks good. 
Not sure how we can calculate values for totalTestCaseCount, passedTestCaseCount & failedTestCaseCount in xml. 

Regarding capture of execution time, I have added comment in Issue (#13) on how we can capture execution time from log file. Let me know if any questions.

**Comment by jeevanjagadeesh** [comment]
@rajeshgrs , we can do this in the code. Once the data is populated in json, we can get the count of pass and fail. Should be simple :+1:

**Comment by rajeshgrs** [comment]
That's great news!

**Comment by jeevanjagadeesh** [comment]
@rajeshgrs , Should only one xml file be generated for one xls?
and should the file name be QATrackerReport.xml?

**Comment by rajeshgrs** [comment]
Yes, for now only -> Testcases written in one workbook should contribute to only on XML. XML file name can be anything.

**Comment by rajeshgrs** [comment]
@jeevanjagadeesh , As a standard practice we use xml file name as QATrackerReport.xml. But I think it makes more sense, if we can append workbook name in the file name. 
 For example: QATrackerReport_oie.xml   for oie.xlsx
                      QATrackerReport_rtm.xml   for rtm.xlsx

Let me know if any queries.

**Comment by jeevanjagadeesh** [comment]
@rajeshgrs , This PR is complete. Have look...

**Comment by rajeshgrs** [comment]
Thanks @jeevanjagadeesh . Sure will go through it.

**Comment by jeevanjagadeesh** [comment]
Time taken is the only param that is hard coded.. Rest are dynamic values.
If you can provide a complete log with Execution time, will make that also dynamic

**Comment by rajeshgrs** [comment]
@jeevanjagadeesh , I actually commented in one of the issues today on how we can pull the execution time. Somehow it is lost I guess. Let me check it.

**Comment by jeevanjagadeesh** [comment]
Its there in the issues. I need complete log file with Execution time

**Comment by rajeshgrs** [comment]
I got that now.
@jeevanjagadeesh , please check issue #13  https://github.com/rajeshgrs/dq-cli/issues/13

**Comment by rajeshgrs** [comment]
@jeevanjagadeesh ,
 I am pasting it again here.

@jeevanjagadeesh ,

I have attached new set of log files that captures execution time. The log information is same as the one I shared before, but it will have some additional lines and the last line will have the pattern as "Execution time: 2.00 s" from which we should extract the time value between "Execution time: " and " s" string patterns.

Please proceed with it as a baseline for framing the code to populate execution time for QATrack report XML.

Let me know if any queries.
File attached here.
[cli_logs.zip](https://github.com/rajeshgrs/dq-cli/files/701684/cli_logs.zip)

**Comment by rajeshgrs** [comment]
Hope you got those required logs.

**Comment by jeevanjagadeesh** [comment]
No , i wont proceed :smile:  ... Proceeding to home :smile:

**Comment by rajeshgrs** [comment]
That was copy paste from comment made in morning. "Proceed' not applicable for now. Enjoy :-)

**Comment by jeevanjagadeesh** [comment]
@rajeshgrs , timeTaken also dynamic. Please test... Also validate if the data population is correct.

**Comment by rajeshgrs** [comment]
Excellent. Let me check.

**Comment by jeevanjagadeesh** [comment]
:moneybag: ? :stuck_out_tongue:

**Comment by rajeshgrs** [comment]
Sure :-)

**Comment by rajeshgrs** [comment]
Hi @jeevanjagadeesh ,
 Thanks.  It looks good. Need some changes.

 Please add few additional attributes and also modify the order in which XML attributes are listed. And the timeTaken value should not capture units "s" in the xml, due  to which total time taken is not working now.

Please refer to current and expected output xml. I have also attached JPEG file showing the comparison and commenting the changes required.

[xmloutput.zip](https://github.com/rajeshgrs/dq-cli/files/702309/xmloutput.zip)

**Referring to jpeg:**
sl.no.1 & 2: Few tags needs to be added
sl.no.3: <timeTaken> should display time units
sl.no. 4: <timeTaken> element under parent tag <TestCase> should populate Total Time Execution Time of all the test cases. (Sorry I missed this demonstrating in pptx document and also in the sample XML that I shared earlier)
sl.no.5: Reorder the tags

**Comment by rajeshgrs** [comment]
@jeevanjagadeesh , If the identified changes are fixed then we are good on generating XML.

**Comment by jeevanjagadeesh** [comment]
@rajeshgrs , Done .

**Comment by rajeshgrs** [comment]
Superb. All the ones mentioned in yesterday's ppt document done?

**Comment by jeevanjagadeesh** [comment]
Think so :laughing:

**Comment by rajeshgrs** [comment]
@jeevanjagadeesh ,
 I mean all these ones w.r.t attached JPEG?
qatrackerreport_current_and_expected_output
.
sl.no.1 & 2: Few tags needs to be added in xml
sl.no.3: Should not display time units
sl.no. 4: element under parent tag should populate Total Time Execution Time of all the test cases. 
sl.no.5: Reorder the tags

**Comment by jeevanjagadeesh** [comment]
Yes :)

**Comment by jeevanjagadeesh** [comment]
image

**Comment by jeevanjagadeesh** [comment]
Attached the xml screenshot

**Comment by rajeshgrs** [comment]
Genius..!!

**Comment by jeevanjagadeesh** [comment]
Then Albert Einstein , Srinivasa Ramanujan :question:

**Comment by jeevanjagadeesh** [comment]
If its working as expected, you can merge. (Click Merge pull request)

**Comment by rajeshgrs** [comment]
I'm still struggling to checkout and synchronize this branch to my local.

**Comment by jeevanjagadeesh** [comment]
just do
1) git checkout log_validator
2) git pull origin log_validator

This should fetch the changes

**Comment by rajeshgrs** [comment]
Ok. I just double checked that total execution time is getting  displayed correctly.
Good to merge the pull request. Let me do it now.

**Pull request merged**
