### PR TITLE
Send email

### PR DESCRIPTION
**Pull request by jeevanjagadeesh**
@rajeshgrs , There was a few path issues in  lib/dqCliLogReader.js. Fixed those in this PR.
 i guess you still have  dqCliLogReader.js in your local root directory, Hence you did not encounter the error.
Also added email code. Replace property ""emailHost": "smtp3.informatica.com" with the your appropriate email host value.

### CODE REVIEW

**Comment by rajeshgrs** [comment]
Something wrong with report generation

image

**Comment by rajeshgrs** [comment]
I think I should replace my local copy of dqCliLogReader.js. 
Will check this sometime. Thanks buddy.

**Comment by jeevanjagadeesh** [comment]
I havent changed that code :disappointed:

**Comment by jeevanjagadeesh** [comment]
Check now. The log path needs to changed to "output\cli_logs"

**Comment by rajeshgrs** [comment]
Thank you. I will check this in evening and get back to you on how it goes
with email program also

**Comment by jeevanjagadeesh** [comment]
Check now.. Pull latest

**Comment by rajeshgrs** [comment]
Still got the same error.
{"name":"dq_cli","hostname":"INW1PC07L0KV","pid":22352,"level":50,"err":{},"msg":"uncaughtException ","time":"2017-01-19T07:18:02.131Z","v":0}

**Comment by rajeshgrs** [comment]
Log snippet.

File written succesfully!!!
{"name":"dq_cli","hostname":"INW1PC07L0KV","pid":22352,"level":30,"msg":"http://psrlxpamqa1:8080/qatrack/servlet/ImportXMLServlet  :qatrackurl","time"
:"2017-01-19T07:17:55.069Z","v":0}
response body == SUCCESS! The Build Report has been added - .<a href="/qatrack/testSuite.jsp?buildReportID=U:aZkxQt4XEea_PPHWXG1qbQ">DQT_ ML_ 10.2.0_
_ ORACLE_ _ importedFromXML_ 1484810276239_#_1_#_0_#_1</a><br>

**{"name":"dq_cli","hostname":"INW1PC07L0KV","pid":22352,"level":50,"err":{},"msg":"uncaughtException ","time":"2017-01-19T07:18:02.131Z","v":0}**

C:\Projects\sendEmail>node dq_cli.js -src oie

**Comment by rajeshgrs** [comment]
Getting error under "composeMail" function.

**Comment by jeevanjagadeesh** [comment]
Did you pull latest ?
Why the response body does not have <a href="/qatrack/testSuite.jsp?buildReportID=?

**Comment by jeevanjagadeesh** [comment]
Ok.. got it.. Make be its stripped in git hub

**Comment by jeevanjagadeesh** [comment]
Can you try now? Pull latest

**Comment by jeevanjagadeesh** [comment]
image

**Comment by rajeshgrs** [comment]
Awesome. Received email :-)

**Comment by jeevanjagadeesh** [comment]
If it looks. Please merge

**Comment by jeevanjagadeesh** [comment]
*looks good

**Pull request merged**
