### PR TITLE
Perform service call, rather than invoking bat file

### PR DESCRIPTION
**Pull request by jeevanjagadeesh**

### CODE REVIEW

**Comment by jeevanjagadeesh** [comment]
@rajeshgrs , added test code to invoke the service with xml data. Can you run the code and post the result.

command - node test.js

**Comment by rajeshgrs** [comment]
I did not get any response by executing "node test.js"

**Comment by jeevanjagadeesh** [comment]
ohh.
Can you remove below if condition from test.js and try?
if (response.statusCode < 200 || response.statusCode > 300) {

**Comment by jeevanjagadeesh** [comment]
Can you pull the latest code and run again?

**Comment by rajeshgrs** [comment]
Ya sure. Let me try now.

**Comment by rajeshgrs** [comment]
Here is the output.

C:\Projects\merge_plugins>node test.js
C:\Projects\merge_plugins\uploadToReport\QATrackerReport-oie.xml
statusCode === 200
response body == FAILED! The Build Report import failed with below exception.<br>Content is not allowed in prolog.

**Comment by jeevanjagadeesh** [comment]
Hehe...

**Comment by jeevanjagadeesh** [comment]
One more try... Please

**Comment by jeevanjagadeesh** [comment]
var request = require('request');
var fs = require('fs');
var path = require('path');
var body1 = '<?xml version="1.0" encoding="utf-8" ?><DSTAutomationReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="buildreport.xsd"><buildNumber>46</buildNumber><branchName>ML</branchName><productVersion>10.2.0</productVersion><executionMode></executionMode><operatingSystem></operatingSystem><databaseType>ORACLE</databaseType><databaseVersion></databaseVersion><buildURL></buildURL><moduleName>DQT</moduleName><buildDate>16-August-2011</buildDate><Installation_Status></Installation_Status><testSuite><name>oie</name><totalTestCaseCount>2</totalTestCaseCount><passedTestCaseCount>1</passedTestCaseCount><failedTestCaseCount>1</failedTestCaseCount><skippedTestCaseCount>0</skippedTestCaseCount><timeTaken>11.694</timeTaken><TestCase><Name>oie-oieexportobjects_1-case1</Name><description></description><status>Failed</status><timeTaken>9.862</timeTaken><exceptionMessage>[ICMD_10033] Command [exportObjects] failed with error [[OIECMD_10006] Error occurred during export function. See previous error.]</exceptionMessage><runLog></runLog></TestCase><TestCase>  <Name>oie-oieimportobjects-case1</Name>   <description></description>   <status>Passed</status>    <timeTaken>1.832</timeTaken>    <exceptionMessage></exceptionMessage>    <runLog></runLog>   </TestCase> </testSuite></DSTAutomationReport>';

var xmlData = path.join(__dirname, 'uploadToReport', '/QATrackerReport-oie.xml');
console.log(xmlData);
var formData = {
  module: 'ATBB',
  xml: body1 //fs.createReadStream(xmlData),
};
//console.log(formData);
request.post({
  url: 'http://psrlxpamqa1:8080/qatrack/servlet/ImportXMLServlet'
  //formData: formData
}, function(error, response, body) {
  if (error) {
    console.log(error);
    process.exit(1);
  }
  //if (response.statusCode < 200 || response.statusCode > 300) {
    console.log('statusCode === ' + response.statusCode);
    console.log('response body == ' + body);
    process.exit(0);
  //}
});

**Comment by jeevanjagadeesh** [comment]
Replace with this code and try.

**Comment by jeevanjagadeesh** [comment]
wait

**Comment by rajeshgrs** [comment]
No luck.

C:\Projects\merge_plugins>node test.js
C:\Projects\merge_plugins\uploadToReport\QATrackerReport-oie.xml
statusCode === 200
response body == FAILED! The Build Report import failed with below
exception.<br>the request doesn't contain a multipart/form-data or
multipart/mixed
stream, content type header is null

**Comment by jeevanjagadeesh** [comment]
just replace line 10
with below

xml: body1 //fs.createReadStream(xmlData),

**Comment by jeevanjagadeesh** [comment]
Looks like the data is getting corrupted. thats why i added the xml directly. so replace line 10 with 
xml: body1

**Comment by rajeshgrs** [comment]
Nope. Still same error.

C:\Projects\merge_plugins>node test.js
C:\Projects\merge_plugins\uploadToReport\QATrackerReport-oie.xml
statusCode === 200
response body == FAILED! The Build Report import failed with below exception.<br>the request doesn't contain a multipart/form-data or multipart/mixed
stream, content type header is null

**Comment by jeevanjagadeesh** [comment]
:disappointed:  .. Ok

**Comment by rajeshgrs** [comment]
Come on. You can do it :-)

**Comment by jeevanjagadeesh** [comment]
Any way,  i can test that service ? :smile:

**Comment by rajeshgrs** [comment]
Nope. It is hosted in intranet.

**Comment by jeevanjagadeesh** [comment]
hmm.. its pain to test.. that's the problem. 
Can you check if the xml on your local system is valid and does not have any errors

**Comment by rajeshgrs** [comment]
Are you saying XML data embedded in the script is corrupeted?

**Comment by jeevanjagadeesh** [comment]
I am guessing that could be the problem.

**Comment by rajeshgrs** [comment]
I can open that xml file in the browser without any parsing errors. I hope that should be enough.

**Comment by jeevanjagadeesh** [comment]
ok

**Comment by rajeshgrs** [comment]
Attached one more sample xml in this zip file. If that helps.
[Remote_Debugging.zip](https://github.com/rajeshgrs/dq-cli/files/710980/Remote_Debugging.zip)

**Comment by rajeshgrs** [comment]
But I don't understand why we are commenting line no.15 //formData: formData

**Comment by jeevanjagadeesh** [comment]
Can you try this?
Line 10 -
xml: fs.createReadStream(xmlData, {encoding:'utf8'}),

**Comment by jeevanjagadeesh** [comment]
i guess, the data posted is getting corrupted

**Comment by rajeshgrs** [comment]
Here is the output:

C:\Projects\merge_plugins>node test.js
C:\Projects\merge_plugins\uploadToReport\QATrackerReport-oie.xml
statusCode === 200
response body == FAILED! The Build Report import failed with below
exception.<br>the request doesn't contain a multipart/form-data or
multipart/mixed
stream, content type header is null

**Comment by rajeshgrs** [comment]
C:\Projects\merge_plugins>node test.js
C:\Projects\merge_plugins\uploadToReport\QATrackerReport-oie.xml
statusCode === 200
response body == FAILED! The Build Report import failed with below exception.<br>Content is not allowed in prolog.

**Comment by jeevanjagadeesh** [comment]
http://stackoverflow.com/questions/2599919/java-parsing-xml-document-gives-content-not-allowed-in-prolog-error

**Comment by rajeshgrs** [comment]
C:\Projects\merge_plugins\uploadToReport\QATrackerReport-oie.xml
string_decoder.js:13
    throw new Error(`Unknown encoding: ${enc}`);
    ^

Error: Unknown encoding: utf16
    at normalizeEncoding (string_decoder.js:13:11)
    at new StringDecoder (string_decoder.js:22:19)
    at new ReadableState (_stream_readable.js:99:20)
    at ReadStream.Readable (_stream_readable.js:108:25)
    at new ReadStream (fs.js:1892:12)
    at Object.fs.createReadStream (fs.js:1870:10)
    at Object.<anonymous> (C:\Projects\merge_plugins\test.js:10:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

C:\Projects\merge_plugins>node test.js
C:\Projects\merge_plugins\uploadToReport\QATrackerReport-oie.xml
string_decoder.js:13
    throw new Error(`Unknown encoding: ${enc}`);
    ^

Error: Unknown encoding: utf-16
    at normalizeEncoding (string_decoder.js:13:11)
    at new StringDecoder (string_decoder.js:22:19)
    at new ReadableState (_stream_readable.js:99:20)
    at ReadStream.Readable (_stream_readable.js:108:25)
    at new ReadStream (fs.js:1892:12)
    at Object.fs.createReadStream (fs.js:1870:10)
    at Object.<anonymous> (C:\Projects\merge_plugins\test.js:10:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

**Comment by jeevanjagadeesh** [comment]
http://stackoverflow.com/questions/3030903/content-is-not-allowed-in-prolog-when-parsing-perfectly-valid-xml-on-gae

**Comment by jeevanjagadeesh** [comment]
xml: fs.readFileSync(xmlData, {encoding:'utf8'}),

**Comment by rajeshgrs** [comment]
<DSTAutomationReport>
  <buildNumber>46</buildNumber>
  <branchName>ML</branchName>
  <productVersion>10.2.0</productVersion>
  <executionMode></executionMode>
  <operatingSystem></operatingSystem>
  <databaseType>ORACLE</databaseType>
  <databaseVersion></databaseVersion>
  <buildURL></buildURL>
  <moduleName>DQT</moduleName>
  <buildDate>16-August-2011</buildDate>
  <Installation_Status></Installation_Status>
  <testSuite>
    <TestCase>
      <Name>oie-oieexportobjects_2-case1</Name>
      <description></description>
      <exceptionMessage></exceptionMessage>
      <status>Passed</status>
      <timeTaken>25</timeTaken>
    </TestCase>
  </testSuite>
  <name>oie</name>
  <totalTestCaseCount>4</totalTestCaseCount>
  <passedTestCaseCount>2</passedTestCaseCount>
  <failedTestCaseCount>2</failedTestCaseCount>
</DSTAutomationReport>

**Comment by rajeshgrs** [comment]
[QATrackerReport-oie.zip](https://github.com/rajeshgrs/dq-cli/files/711090/QATrackerReport-oie.zip)

**Comment by rajeshgrs** [comment]
<DSTAutomationReport>
  <buildNumber>46</buildNumber>  
</DSTAutomationReport>

**Comment by rajeshgrs** [comment]
C:\Projects\merge_plugins>node test.js
C:\Projects\merge_plugins\uploadToReport\QATrackerReport-oie.xml
statusCode === 200
response body == FAILED! The Build Report import failed with below exception.<br>Content is not allowed in prolog.

**Comment by jeevanjagadeesh** [comment]
@rajeshgrs , Pushed another change.. Can you pull latest and try one last time for today :)

**Comment by jeevanjagadeesh** [comment]
'Content-Type':

**Comment by rajeshgrs** [comment]
C:\Projects\merge_plugins>node test.js
C:\Projects\merge_plugins\uploadToReport\QATrackerReport-oie.xml
FAILED! The Build Report import failed with below exception.<br>the request doesn't contain a multipart/form-data or multipart/mixed stream, content t
ype header is null
statusCode === 200
response body == FAILED! The Build Report import failed with below exception.<br>the request doesn't contain a multipart/form-data or multipart/mixed
stream, content type header is null

**Comment by rajeshgrs** [comment]
'Content-Type':multipart/form-data

**Comment by rajeshgrs** [comment]
C:\Projects\merge_plugins>node test.js
C:\Projects\merge_plugins\uploadToReport\QATrackerReport-oie.xml
SUCCESS! The Build Report has been added - .<a href="/qatrack/testSuite.jsp?buildReportID=U:A1-hydy8Eea_PPHWXG1qbQ">_ _ _ _ _ _ importedFromXML_ 14846
61069162_#_0_#_0_#_0</a><br>
statusCode === 200
response body == SUCCESS! The Build Report has been added - .<a href="/qatrack/testSuite.jsp?buildReportID=U:A1-hydy8Eea_PPHWXG1qbQ">_ _ _ _ _ _ impor
tedFromXML_ 1484661069162_#_0_#_0_#_0</a><br>

**Comment by rajeshgrs** [comment]
image

**Comment by rajeshgrs** [comment]
image

**Comment by rajeshgrs** [comment]
image

**Comment by rajeshgrs** [comment]
/qatrack/testSuite.jsp?buildReportID=U:q5HMbty8Eea_PPHWXG1qbQ

**Comment by rajeshgrs** [comment]
From above response body, 
we need to extract 
"/qatrack/testSuite.jsp?buildReportID=U:q5HMbty8Eea_PPHWXG1qbQ" 
and append this with hardcoded value 
"http://psrlxpamqa1:8080/qatrack/servlet/ImportXMLServlet" 
to generate final qa track url: 
"http://psrlxpamqa1:8080/qatrack/testSuite.jsp?buildReportID=U:q5HMbty8Eea_PPHWXG1qbQ"
This URL will be used in Email Program

**Comment by rajeshgrs** [comment]
response body == SUCCESS! The Build Report has been added - .<a href="/qatrack/testSuite.jsp?buildReportID=U:q5HMbty8Eea_PPHWXG1qbQ">DQT_ ML_ 10.2.0__ ORACLE_ _ importedFromXML_ 1484661351348_#_1_#_0_#_1</a><br>

From above response body, 
we need to extract 
"/qatrack/testSuite.jsp?buildReportID=U:q5HMbty8Eea_PPHWXG1qbQ" 
and append this with hardcoded value 
"http://psrlxpamqa1:8080/qatrack/servlet/ImportXMLServlet" 
to generate final qa track url: 
"http://psrlxpamqa1:8080/qatrack/testSuite.jsp?buildReportID=U:q5HMbty8Eea_PPHWXG1qbQ"
This URL will be used in Email Program

**Comment by jeevanjagadeesh** [comment]
Pull latest and run dq_cli.js.

**Comment by rajeshgrs** [comment]
sure.

**Comment by jeevanjagadeesh** [comment]
Merging..

**Pull request merged**
