### PR TITLE
expose log reader as libary

### PR DESCRIPTION
**Pull request by jeevanjagadeesh**
https://github.com/rajeshgrs/dq-cli/issues/16
https://github.com/rajeshgrs/dq-cli/issues/17

### CODE REVIEW

**Comment by jeevanjagadeesh** [comment]
@rajeshgrs , Please test

**Comment by jeevanjagadeesh** [comment]
I assume, at any point of time (i.e when dq_cli.js is invoked) only one batch/sh file would be invoked for execution (e.g oie.bat)

**Comment by rajeshgrs** [comment]
Hi @jeevanjagadeesh , Worked fine during the tests. Good to merge. Let me Pull Merge request

**Comment by jeevanjagadeesh** [comment]
is it working fine???

**Comment by rajeshgrs** [comment]
Yes Buddy. It is working fine.

**Comment by jeevanjagadeesh** [comment]
i had a question -
http://psrlxpamqa1:8080/qatrack/servlet/ImportXMLServlet  is a service hosted , which requires xml content in request body ?
or is it a standalone java code, which takes data as arguments?

**Comment by jeevanjagadeesh** [comment]
looking at the ImportXML java code, i guess the service is hosted

**Comment by rajeshgrs** [comment]
You're right. http://psrlxpamqa1:8080/qatrack
<http://psrlxpamqa1:8080/qatrack/servlet/ImportXMLServlet> is a service
hosted somewhere- called to be a reporting tool server. Our Java code
\log_validator\QATrackImport included in our nodejs program takes arguments
from us and send the data to this service to get a Reporting URL as a
response.

**Comment by jeevanjagadeesh** [comment]
We can do a direct service call from node js, instead of invoking a java code and that invoking service.
In which case, we can get rid of the java code (QATrackImport) from code base

**Comment by rajeshgrs** [comment]
That will be real awesome.

**Comment by jeevanjagadeesh** [comment]
Can you install the below plugin in chrome and try to invoke the service with post method and share the screen shot of the result. So i can change the code accordingly
https://chrome.google.com/webstore/detail/dhc-restlet-client/aejoelaoggembcahagimdiliamlcdmfm?hl=en

**Comment by jeevanjagadeesh** [comment]
image

**Comment by rajeshgrs** [comment]
ok sure let me try that.

**Comment by rajeshgrs** [comment]
Got below response

[image: Inline image 1]

**Comment by rajeshgrs** [comment]
@jeevanjagadeesh , Here is the response. 

image

**Comment by jeevanjagadeesh** [comment]
Ok .. Got it. Service expects a multipart data

**Comment by jeevanjagadeesh** [comment]
Can you try this?

image

**Comment by rajeshgrs** [comment]
Ultimate Guru.

Input:
image

Output:
image

**Comment by rajeshgrs** [comment]
So from the response received, we should extract "/qatrack/testSuite.jsp?buildReportID=U:A21QndysEea_PPHWXG1qbQ" and append to hardcode value "http://psrlxpamqa1:8080" to get full URL "http://psrlxpamqa1:8080/qatrack/testSuite.jsp?buildReportID=U:A21QndysEea_PPHWXG1qbQ" which is supposed to be sent in email.

**Comment by jeevanjagadeesh** [comment]
hmm.. 
I just pushed the changed code to Pull request, can u test the code and see, if it works?

**Pull request merged**
