### PR TITLE
Rajesh 9jan2017

### PR DESCRIPTION
**Pull request by rajeshgrs**
1) There are some small changes made to the code to enable uploading of XML(Format in which test result is uploaded to reporting tool called QATrack)

2) Partially working /lib/sendmail.js which is not able to return value to the calling method due to some bug in code.

### CODE REVIEW

**Comment by jeevanjagadeesh** [comment]
This branch has conflicts that must be resolved
Use the web editor or the command line to resolve conflicts.
Conflicting files
dq_cli.js
lib/excel2Json.js
package.json

Conflicts resolved thr command line
git checkout master
git pull origin master
git checkout rajesh_9jan2017
git merge master

resolve the conflicts manually and push the changes

**Comment by rajeshgrs** [comment]
Please try again now.

**Comment by jeevanjagadeesh** [comment]
:(  I resolved the changes and pushed :)
You again pushed some changes which again resulted in conflicts

**Comment by jeevanjagadeesh** [comment]
My bad. I should have put "Pushed the changes" . Typo :)

**Comment by rajeshgrs** [comment]
Oops. Yes, I thought you asked me to push :-)

**Comment by jeevanjagadeesh** [comment]
Merging this PR. I have not tested :disappointed: .
Hope you (@rajeshgrs ) tested and it works :)

**Pull request merged**
